config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root', via: :get
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Device < ActiveRecord::Base
  validates :user, :name, presence: true
  validates :name, uniqueness: { scope: :user }

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  session_token   :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  has_many :devices

  validates :email, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password

  before_validation :ensure_session_token

  def self.with_credentials(creds)
    user = User.find_by(email: creds[:email])
    if user && user.is_password?(creds[:password])
      user
    else
      nil
    end
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.hex
    save!
    session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.hex
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Authable
end

app/controllers/concerns/authable.rb
module Authable
  extend ActiveSupport::Concern

  included do
    helper_method :current_user, :signed_in?
  end

  def signed_in?
    !!current_user
  end

  def current_user
    @_current_user ||= User.find_by(session_token: session[:token])
  end

  def sign_in!(user)
    session[:token] = user.reset_session_token!
  end

  def sign_out!
    current_user.reset_session_token!
    session[:token] = nil
  end

  def require_user!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.with_credentials(user_params)
    if @user
      sign_in!(@user)
      redirect_to root_url
    else
      @user = User.new
      flash.now[:errors] = ['Invalid email and/or password']
      render :new
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_user!

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/devices/_device.html.erb
<li><%= device.name %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remote Switch</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>

<%= yield %>

</body>
</html>

app/views/static_pages/root.html.erb
<h2>Welcome, <%= current_user.email %></h2>

<h1>Devices</h1>

<ul class="devices">
  <%= render current_user.devices %>
</ul>

app/views/users/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Email<br>
    <input type="email" name="user[email]" value="<%= @user.email %>">
  </label>

  <label>Password<br>
    <input type="text" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">
</form>